version: "3.8"

services:
  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    ports:
      - "8080:3000"
    environment:
      - MONGO_URI=mongodb://test:test@mongodb:27017
      - JWT_SECRET=test
    depends_on:
      - mongodb

  event-server:
    build:
      context: ./event-server
      dockerfile: Dockerfile
    container_name: event-server
    ports:
      - "8081:3000"
    environment:
      - MONGO_URI=mongodb://test:test@mongodb:27017
      - AUTH_URI=http://auth-server:3000
    depends_on:
      - mongodb
      - auth-server

  gw-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    container_name: gw-server
    ports:
      - "8082:3000"
    environment:
      - MONGO_URI=mongodb://test:test@mongodb:27017
      - AUTH_SERVER_URI=http://auth-server:3000
      - EVENT_SERVER_URI='http://event-server:3000
    depends_on:
      - mongodb
      - auth-server
      - event-server

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
